INSERT
    INTO
        users(
            tenant_id,
            username,
            email
        )
    VALUES(
        'tenant_A',
        'johndoe',
        'johndoe@example.com'
    ),
    (
        'tenant_A',
        'janedoe',
        'janedoe@example.com'
    ),
    (
        'tenant_A',
        'alice123',
        'alice123@example.com'
    ),
    (
        'tenant_B',
        'bob_smith',
        'bob_smith@example.com'
    ),
    (
        'tenant_B',
        'charlie_b',
        'charlie_b@example.com'
    ),
    (
        'tenant_B',
        'danielle',
        'danielle@example.com'
    ),
    (
        'tenant_C',
        'edward92',
        'edward92@example.com'
    ),
    (
        'tenant_C',
        'fiona_lee',
        'fiona_lee@example.com'
    ),
    (
        'tenant_C',
        'george.k',
        'george.k@example.com'
    ),
    (
        'tenant_C',
        'hannah_w',
        'hannah_w@example.com'
    );

INSERT
    INTO
        orders(
            user_id,
            tenant_id,
            product,
            quantity
        )
    VALUES(
        1,
        'tenant_A',
        'Laptop',
        2
    ),
    (
        2,
        'tenant_A',
        'Smartphone',
        1
    ),
    (
        3,
        'tenant_A',
        'Tablet',
        3
    ),
    (
        4,
        'tenant_B',
        'Monitor',
        2
    ),
    (
        5,
        'tenant_B',
        'Keyboard',
        5
    ),
    (
        6,
        'tenant_B',
        'Mouse',
        4
    ),
    (
        7,
        'tenant_C',
        'Headphones',
        2
    ),
    (
        8,
        'tenant_C',
        'Smartwatch',
        1
    ),
    (
        9,
        'tenant_C',
        'Desk Chair',
        2
    ),
    (
        10,
        'tenant_C',
        'External HDD',
        3
    );
